export const routes = {
  ACCOUNTS: "/auth/accounts",
  SIGNUP: "/auth/signup",
  LOGIN: "/auth/login",
  VERIFY: "/auth/verify",
  RESET: "/auth/reset",
  FORGOT: "/auth/forgot",
  CALLBACK_SIGNUP: "/auth/callback-signup",
  CALLBACK_SIGNIN: "/auth/callback-signin",
  CALLBACK_CONNECT: "/callback-connect",

  ONBOARD: "/auth/onboard",
  ACCESS: "/auth/access",
  CHUNK: "/chunk",

  HOME: "/",
  DASHBOARD: "/dashboard",
  CONSULTATIONS: "/consultations",
  OFFICER_HOURS: "/office-hours",
  DOCU_SIGN: "/docu-scan",
  MATTERS: "/matters",
  DOCUMENTS: "/documents",
  CLIENTS: "/clients",
  LAW_FIRM: "/law-firm",
  SETTINGS: "/settings",
};
